name: Release

on:
  push:
    tags:
      - 'release/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set build variables
      run: |
        GIT_VER=${GITHUB_REF##*/}
        GIT_TAG=${GITHUB_REF##refs/tags/}
        if [[ ${GIT_VER} =~ ^[0-9]+[.][0-9]+[.][0-9]+[-][A-Za-z0-9]+ ]]
        then
          GH_TYPE='Release Candidate'
        else
          GH_TYPE='Release'
        fi
        echo "GIT_VER=${GIT_VER}" >> ${GITHUB_ENV}
        echo "GIT_TAG=${GIT_TAG}" >> ${GITHUB_ENV}
        echo "GH_TYPE=${GH_TYPE}" >> ${GITHUB_ENV}
        cat ${GITHUB_ENV}

    - name: Make release package
      run: zip -q -r "rotorflight-lua-scripts-${{ env.GIT_VER }}.zip" RF*

    - name: Create Release
      run: |
        gh release create ${{ env.GIT_TAG }} --notes-file "Release.md" --title "Rotorflight LUA Scripts for Ethos ${{ env.GH_TYPE }} ${{ env.GIT_VER }}" *.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

