name: Snapshot

on:
  push:
    tags:
      - 'snapshot/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set build variables
      run: |
        echo "GIT_VER=${GITHUB_REF##*/}" >> ${GITHUB_ENV}
        echo "GIT_TAG=${GITHUB_REF##refs/tags/}" >> ${GITHUB_ENV}
        cat ${GITHUB_ENV}

    - name: Make snapshot package
      run: zip -q -r "rotorflight-lua-scripts-${{ env.GIT_VER }}.zip" RF*

    - name: Create Snapshot
      run: |
        gh release create ${{ env.GIT_TAG }} --prerelease --notes-file "Snapshot.md" --title "Rotorflight LUA Scripts Snapshot ${{ env.GIT_VER }}" *.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

